from .lora_example_prompt import NODE_CLASS_MAPPINGS as PROMPT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY
from .multi_lora_loader import NODE_CLASS_MAPPINGS as MULTI_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MULTI_DISPLAY

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

# Register LoRA Example Prompt Node
NODE_CLASS_MAPPINGS.update(PROMPT_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PROMPT_DISPLAY)

# Register Multi LoRA Loader Node
NODE_CLASS_MAPPINGS.update(MULTI_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MULTI_DISPLAY)
